In [2]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

client = CryptoHistoricalDataClient()
client

# Get data

In [3]:
request_params = CryptoBarsRequest(
  symbol_or_symbols=["BTC/USD"],
  timeframe=TimeFrame.Hour,
  start=datetime(2024, 1, 1),
  end=datetime(2025, 12, 31)
)

btc_bars = client.get_crypto_bars(request_params)
btc_bars = btc_bars.df

btc_bars

                                         open        high         low  \
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42274.0850  42526.9850  42264.4130
        2024-01-01 01:00:00+00:00  42459.8000  42761.5590  42416.1650
        2024-01-01 02:00:00+00:00  42618.3550  42630.5390  42503.8755
        2024-01-01 03:00:00+00:00  42562.5500  42586.4700  42244.1600
        2024-01-01 04:00:00+00:00  42323.3050  42388.6750  42205.5015
...                                       ...         ...         ...
        2025-12-30 20:00:00+00:00  88145.3150  88152.1645  87768.5300
        2025-12-30 21:00:00+00:00  87862.4800  88263.7050  87787.7100
        2025-12-30 22:00:00+00:00  88192.9390  88399.0270  88177.4000
        2025-12-30 23:00:00+00:00  88336.9565  88499.6500  88267.8575
        2025-12-31 00:00:00+00:00  88400.9845  88409.0295  88143.1550

                                        close    volume  trade_count  \
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42469.8850  0.000024          1.0
        2024-01-01 01:00:00+00:00  42601.2530  0.000364          2.0
        2024-01-01 02:00:00+00:00  42563.6835  0.000127          2.0
        2024-01-01 03:00:00+00:00  42332.0085  0.000223          2.0
        2024-01-01 04:00:00+00:00  42388.6750  0.000023          1.0
...                                       ...       ...          ...
        2025-12-30 20:00:00+00:00  87864.1985  0.029009         49.0
        2025-12-30 21:00:00+00:00  88194.9700  0.100728          4.0
        2025-12-30 22:00:00+00:00  88348.8940  0.044494          9.0
        2025-12-30 23:00:00+00:00  88395.2680  0.005779         11.0
        2025-12-31 00:00:00+00:00  88165.7185  0.002744          5.0

                                           vwap
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42461.517000
        2024-01-01 01:00:00+00:00  42733.877938
        2024-01-01 02:00:00+00:00  42556.883239
        2024-01-01 03:00:00+00:00  42338.815531
        2024-01-01 04:00:00+00:00  42337.461000
...                                         ...
        2025-12-30 20:00:00+00:00  87998.159885
        2025-12-30 21:00:00+00:00  88135.003538
        2025-12-30 22:00:00+00:00  88306.825015
        2025-12-30 23:00:00+00:00  88430.278091
        2025-12-31 00:00:00+00:00  88315.515747

[17518 rows x 7 columns]

In [4]:
btc_bars['Result'] = np.where(btc_bars['close'] > btc_bars['open'], 1, 0)
btc_bars['Result'].mean()

np.float64(0.5009133462724056)

# Transform data

In [5]:
for i in range(5):
    btc_bars[f"hour_{i+1}"] = btc_bars['Result'].shift(i+1).astype('Int64')

btc_bars = btc_bars.dropna()
btc_bars.head()

                                         open        high         low  \
symbol  timestamp
BTC/USD 2024-01-01 05:00:00+00:00  42374.6160  42374.6160  42183.9675
        2024-01-01 06:00:00+00:00  42212.5700  42434.1600  42212.5700
        2024-01-01 07:00:00+00:00  42427.1540  42506.3980  42427.1540
        2024-01-01 08:00:00+00:00  42497.6885  42555.1355  42467.2515
        2024-01-01 09:00:00+00:00  42563.2860  42691.2500  42541.7800

                                        close    volume  trade_count  \
symbol  timestamp
BTC/USD 2024-01-01 05:00:00+00:00  42214.8000  0.002391          3.0
        2024-01-01 06:00:00+00:00  42412.3500  0.000268          2.0
        2024-01-01 07:00:00+00:00  42497.3710  0.000155          2.0
        2024-01-01 08:00:00+00:00  42555.1355  0.000023          1.0
        2024-01-01 09:00:00+00:00  42639.7550  0.000865          3.0

                                           vwap  Result  hour_1  hour_2  \
symbol  timestamp
BTC/USD 2024-01-01 05:00:00+00:00  42265.037806       0       1       0
        2024-01-01 06:00:00+00:00  42374.150553       1       0       1
        2024-01-01 07:00:00+00:00  42488.393433       1       1       0
        2024-01-01 08:00:00+00:00  42509.101000       1       1       1
        2024-01-01 09:00:00+00:00  42671.530403       1       1       1

                                   hour_3  hour_4  hour_5
symbol  timestamp
BTC/USD 2024-01-01 05:00:00+00:00       0       1       1
        2024-01-01 06:00:00+00:00       0       0       1
        2024-01-01 07:00:00+00:00       1       0       0
        2024-01-01 08:00:00+00:00       0       1       0
        2024-01-01 09:00:00+00:00       1       0       1

In [6]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Prepare your data
btc_bars['date'] = pd.to_datetime(btc_bars.index.get_level_values(1))
btc_bars = btc_bars.sample(frac=1)

# Define features (X) and target (y)
X = btc_bars[['open', 'high', 'low', 'close', 'hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']]
y = btc_bars['Result']

# 2. Split data by date
# Example: 70% Train, 15% Validation, 15% Test
n = len(btc_bars)
train_end = int(n * 0.70)
val_end = int(n * 0.85)

X_train, y_train = X.iloc[:train_end], y.iloc[:train_end]
X_val, y_val = X.iloc[train_end:val_end], y.iloc[train_end:val_end]
X_test, y_test = X.iloc[val_end:], y.iloc[val_end:]

# 3. Build and Train the Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=54)
clf.fit(X_train[['hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']], y_train)

# 4. Evaluate the model
val_preds = clf.predict(X_val[['hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']])
print("Validation Accuracy:", accuracy_score(y_val, val_preds))

# Performance
test_preds = clf.predict(X_test[['hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']])
print("Test Accuracy:", accuracy_score(y_test, test_preds))
print(classification_report(y_test, test_preds))

C:\Users\Stan\AppData\Local\Temp\ipykernel_4592\4193359656.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  btc_bars['date'] = pd.to_datetime(btc_bars.index.get_level_values(1))

Validation Accuracy: 0.5081842405786068
Test Accuracy: 0.5215074229158736
              precision    recall  f1-score   support

           0       0.52      0.46      0.48      1295
           1       0.53      0.59      0.55      1332

    accuracy                           0.52      2627
   macro avg       0.52      0.52      0.52      2627
weighted avg       0.52      0.52      0.52      2627

In [7]:
results = pd.DataFrame({'Open': X_test['open'], 'Close': X_test['close'], 'Actual': y_test, 'Predicted': test_preds})
results['Result'] = np.where(results['Actual'] == results['Predicted'], 1, 0)
results['difference'] = (results['Close'] - results['Open']) / results['Open']

results['Year'] = results.index.get_level_values(1).year
results['Month'] = results.index.get_level_values(1).month
results

                                          Open        Close  Actual  \
symbol  timestamp
BTC/USD 2024-07-23 16:00:00+00:00   66635.2925   65871.7800       0
        2024-04-26 13:00:00+00:00   64094.3015   64485.4600       1
        2024-04-24 00:00:00+00:00   66430.9200   66735.6355       1
        2025-07-04 06:00:00+00:00  109017.2235  109074.1820       1
        2025-03-20 04:00:00+00:00   85964.3260   85698.5800       0
...                                        ...          ...     ...
        2024-09-14 03:00:00+00:00   60359.0250   60352.2885       0
        2025-09-20 00:00:00+00:00  115685.4585  115780.9985       1
        2025-05-31 22:00:00+00:00  104913.8800  104658.0100       0
        2024-03-23 01:00:00+00:00   63625.9335   64103.4120       1
        2025-04-23 21:00:00+00:00   93632.1210   93519.4500       0

                                   Predicted  Result  difference  Year  Month
symbol  timestamp
BTC/USD 2024-07-23 16:00:00+00:00          1       0   -0.011458  2024      7
        2024-04-26 13:00:00+00:00          1       1    0.006103  2024      4
        2024-04-24 00:00:00+00:00          0       0    0.004587  2024      4
        2025-07-04 06:00:00+00:00          1       1    0.000522  2025      7
        2025-03-20 04:00:00+00:00          1       0   -0.003091  2025      3
...                                      ...     ...         ...   ...    ...
        2024-09-14 03:00:00+00:00          1       0   -0.000112  2024      9
        2025-09-20 00:00:00+00:00          0       0    0.000826  2025      9
        2025-05-31 22:00:00+00:00          1       0   -0.002439  2025      5
        2024-03-23 01:00:00+00:00          1       1    0.007504  2024      3
        2025-04-23 21:00:00+00:00          0       1   -0.001203  2025      4

[2627 rows x 8 columns]

In [8]:
# Average accuracy
results['Result'].mean(), results['Actual'].mean(), results['Predicted'].mean()

(np.float64(0.5215074229158736),
 np.float64(0.5070422535211268),
 np.float64(0.5652835934526076))

In [9]:
# Calculate per year and month the number of rows and the accuracy
results.groupby('Year').agg(
    Trades=('Result', 'size'),
    Positive_trades=('Predicted', 'sum'),
    Accuracy=('Result', 'mean')
).reset_index()

   Year  Trades  Positive_trades  Accuracy
0  2024    1349              754  0.535211
1  2025    1278              731  0.507042

In [10]:
# Calculate the total percentage gain based on the predictions and add print it as a percentage
str(round((results[results['Predicted'] == 1].difference.sum() - results[results['Predicted'] == 0].difference.sum())*100, 1)) + '%'

'19.2%'

# Save model

In [11]:
from joblib import dump

dump(clf, "Models/RF_20260129.joblib")

['Models/RF_20260129.joblib']