In [1]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame

client = CryptoHistoricalDataClient()
client

# Get data

In [2]:
request_params = CryptoBarsRequest(
  symbol_or_symbols=["BTC/USD"],
  timeframe=TimeFrame.Hour,
  start=datetime(2024, 1, 1),
  end=datetime(2025, 12, 31)
)

btc_bars = client.get_crypto_bars(request_params)
btc_bars = btc_bars.df

btc_bars

                                         open        high         low  \
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42274.0850  42526.9850  42264.4130
        2024-01-01 01:00:00+00:00  42459.8000  42761.5590  42416.1650
        2024-01-01 02:00:00+00:00  42618.3550  42630.5390  42503.8755
        2024-01-01 03:00:00+00:00  42562.5500  42586.4700  42244.1600
        2024-01-01 04:00:00+00:00  42323.3050  42388.6750  42205.5015
...                                       ...         ...         ...
        2025-12-30 20:00:00+00:00  88145.3150  88152.1645  87768.5300
        2025-12-30 21:00:00+00:00  87862.4800  88263.7050  87787.7100
        2025-12-30 22:00:00+00:00  88192.9390  88399.0270  88177.4000
        2025-12-30 23:00:00+00:00  88336.9565  88499.6500  88267.8575
        2025-12-31 00:00:00+00:00  88400.9845  88409.0295  88143.1550

                                        close    volume  trade_count  \
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42469.8850  0.000024          1.0
        2024-01-01 01:00:00+00:00  42601.2530  0.000364          2.0
        2024-01-01 02:00:00+00:00  42563.6835  0.000127          2.0
        2024-01-01 03:00:00+00:00  42332.0085  0.000223          2.0
        2024-01-01 04:00:00+00:00  42388.6750  0.000023          1.0
...                                       ...       ...          ...
        2025-12-30 20:00:00+00:00  87864.1985  0.029009         49.0
        2025-12-30 21:00:00+00:00  88194.9700  0.100728          4.0
        2025-12-30 22:00:00+00:00  88348.8940  0.044494          9.0
        2025-12-30 23:00:00+00:00  88395.2680  0.005779         11.0
        2025-12-31 00:00:00+00:00  88165.7185  0.002744          5.0

                                           vwap
symbol  timestamp
BTC/USD 2024-01-01 00:00:00+00:00  42461.517000
        2024-01-01 01:00:00+00:00  42733.877938
        2024-01-01 02:00:00+00:00  42556.883239
        2024-01-01 03:00:00+00:00  42338.815531
        2024-01-01 04:00:00+00:00  42337.461000
...                                         ...
        2025-12-30 20:00:00+00:00  87998.159885
        2025-12-30 21:00:00+00:00  88135.003538
        2025-12-30 22:00:00+00:00  88306.825015
        2025-12-30 23:00:00+00:00  88430.278091
        2025-12-31 00:00:00+00:00  88315.515747

[17518 rows x 7 columns]

In [24]:
btc_bars['percentage_diff'] = (btc_bars['close'] - btc_bars['open']) / btc_bars['open'] * 100
btc_bars['target'] = np.where(btc_bars['percentage_diff'] > 0, 1, 0)

btc_bars['positive_diff'] = (btc_bars['percentage_diff'] > 0).astype(int)
btc_bars

                                          open         high            low  \
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00   59657.0685   59820.7145   59622.265000
        2024-12-19 07:00:00+00:00  101136.2000  101677.1200  101105.418500
        2025-01-03 23:00:00+00:00   98306.0185   98357.2190   98015.070000
        2024-03-27 21:00:00+00:00   68923.4430   69233.4400   68904.000000
        2025-08-01 22:00:00+00:00  113924.2250  113962.9880  112727.079803
...                                        ...          ...            ...
        2024-02-08 17:00:00+00:00   45058.4550   45248.9925   44889.990000
        2025-07-26 17:00:00+00:00  118182.7100  118182.7100  118017.860000
        2024-05-06 07:00:00+00:00   64242.9655   64591.5940   64186.075000
        2025-12-15 12:00:00+00:00   89653.8650   89800.5160   89420.559000
        2024-11-25 13:00:00+00:00   98000.0000   98000.0000   97266.460000

                                         close    volume  trade_count  \
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00   59741.3450  0.208187          2.0
        2024-12-19 07:00:00+00:00  101638.2380  0.046276          8.0
        2025-01-03 23:00:00+00:00   98119.2565  0.210411          2.0
        2024-03-27 21:00:00+00:00   68913.7450  0.001460          4.0
        2025-08-01 22:00:00+00:00  113086.5050  0.010470          9.0
...                                        ...       ...          ...
        2024-02-08 17:00:00+00:00   45037.2150  0.069395          9.0
        2025-07-26 17:00:00+00:00  118099.7055  0.041655         10.0
        2024-05-06 07:00:00+00:00   64552.4500  0.014283          1.0
        2025-12-15 12:00:00+00:00   89716.8500  0.056616          8.0
        2024-11-25 13:00:00+00:00   97539.8535  0.129307         15.0

                                            vwap  percentage_diff  Result  \
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00   59694.150214         0.141268       1
        2024-12-19 07:00:00+00:00  101465.832929         0.496398       1
        2025-01-03 23:00:00+00:00   98015.703532        -0.189980       0
        2024-03-27 21:00:00+00:00   69230.073143        -0.014071       0
        2025-08-01 22:00:00+00:00  113011.026431        -0.735331       0
...                                          ...              ...     ...
        2024-02-08 17:00:00+00:00   45080.621889        -0.047139       0
        2025-07-26 17:00:00+00:00  118126.340959        -0.070234       0
        2024-05-06 07:00:00+00:00   64296.548000         0.481741       1
        2025-12-15 12:00:00+00:00   89741.473200         0.070254       1
        2024-11-25 13:00:00+00:00   97574.395066        -0.469537       0

                                   target  positive_diff  hour_1  hour_2  \
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00       1              1       0       0
        2024-12-19 07:00:00+00:00       1              1       0       1
        2025-01-03 23:00:00+00:00       0              0       1       1
        2024-03-27 21:00:00+00:00       0              0       1       0
        2025-08-01 22:00:00+00:00       0              0       1       0
...                                   ...            ...     ...     ...
        2024-02-08 17:00:00+00:00       0              0       1       1
        2025-07-26 17:00:00+00:00       0              0       0       1
        2024-05-06 07:00:00+00:00       1              1       0       0
        2025-12-15 12:00:00+00:00       1              1       1       0
        2024-11-25 13:00:00+00:00       0              0       0       0

                                   hour_3  hour_4  hour_5  \
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00       1       0       1
        2024-12-19 07:00:00+00:00       1       1       0
        2025-01-03 23:00:00+00:00       1       1       0
        2024-03-27 21:00:00+00:00       1       0       1
        2025-08-01 22:00:00+00:00       0       1       0
...                                   ...     ...     ...
        2024-02-08 17:00:00+00:00       1       1       1
        2025-07-26 17:00:00+00:00       0       1       0
        2024-05-06 07:00:00+00:00       0       0       0
        2025-12-15 12:00:00+00:00       1       1       0
        2024-11-25 13:00:00+00:00       0       0       0

                                                       date
symbol  timestamp
BTC/USD 2024-07-14 13:00:00+00:00 2024-07-14 13:00:00+00:00
        2024-12-19 07:00:00+00:00 2024-12-19 07:00:00+00:00
        2025-01-03 23:00:00+00:00 2025-01-03 23:00:00+00:00
        2024-03-27 21:00:00+00:00 2024-03-27 21:00:00+00:00
        2025-08-01 22:00:00+00:00 2025-08-01 22:00:00+00:00
...                                                     ...
        2024-02-08 17:00:00+00:00 2024-02-08 17:00:00+00:00
        2025-07-26 17:00:00+00:00 2025-07-26 17:00:00+00:00
        2024-05-06 07:00:00+00:00 2024-05-06 07:00:00+00:00
        2025-12-15 12:00:00+00:00 2025-12-15 12:00:00+00:00
        2024-11-25 13:00:00+00:00 2024-11-25 13:00:00+00:00

[17503 rows x 17 columns]

In [25]:
btc_bars['target'].mean()

np.float64(0.5009426955379078)

# Transform data

In [26]:
for i in range(5):
    btc_bars[f"hour_{i+1}"] = btc_bars['positive_diff'].shift(i+1).astype('Int64')

btc_bars = btc_bars.dropna()
btc_bars.head()

                                          open         high          low  \
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00  106872.0300  106971.6220  106796.2800
        2024-03-25 11:00:00+00:00   67016.5005   67034.2505   66807.1855
        2024-11-14 05:00:00+00:00   90160.9745   90186.6500   89752.6100
        2024-09-15 16:00:00+00:00   60368.3265   60399.5840   59947.9635
        2025-06-23 06:00:00+00:00  101909.7200  102094.8500  101717.7465

                                         close    volume  trade_count  \
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00  106903.5765  0.007490          5.0
        2024-03-25 11:00:00+00:00   66841.5210  0.000100          1.0
        2024-11-14 05:00:00+00:00   90051.4400  0.088871          8.0
        2024-09-15 16:00:00+00:00   59947.9635  0.039275          6.0
        2025-06-23 06:00:00+00:00  102006.7950  0.549327         13.0

                                            vwap  percentage_diff  Result  \
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00  106890.138548         0.029518       1
        2024-03-25 11:00:00+00:00   66873.500000        -0.261099       0
        2024-11-14 05:00:00+00:00   90032.985230        -0.121488       0
        2024-09-15 16:00:00+00:00   60210.522702        -0.696330       0
        2025-06-23 06:00:00+00:00  101922.855724         0.095256       1

                                   target  positive_diff  hour_1  hour_2  \
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00       1              1       0       0
        2024-03-25 11:00:00+00:00       0              0       1       0
        2024-11-14 05:00:00+00:00       0              0       0       1
        2024-09-15 16:00:00+00:00       0              0       0       0
        2025-06-23 06:00:00+00:00       1              1       0       0

                                   hour_3  hour_4  hour_5  \
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00       0       1       1
        2024-03-25 11:00:00+00:00       0       0       1
        2024-11-14 05:00:00+00:00       0       0       0
        2024-09-15 16:00:00+00:00       1       0       0
        2025-06-23 06:00:00+00:00       0       1       0

                                                       date
symbol  timestamp
BTC/USD 2025-07-01 06:00:00+00:00 2025-07-01 06:00:00+00:00
        2024-03-25 11:00:00+00:00 2024-03-25 11:00:00+00:00
        2024-11-14 05:00:00+00:00 2024-11-14 05:00:00+00:00
        2024-09-15 16:00:00+00:00 2024-09-15 16:00:00+00:00
        2025-06-23 06:00:00+00:00 2025-06-23 06:00:00+00:00

In [27]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Prepare your data
btc_bars['date'] = pd.to_datetime(btc_bars.index.get_level_values(1))
btc_bars = btc_bars.sample(frac=1)

# Define features (X) and target (y)
X = btc_bars[['open', 'high', 'low', 'close', 'hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']]
y = btc_bars['target']

# 2. Split data by date
# Example: 75% Train, 25% Test
n = len(btc_bars)
train_end = int(n * 0.75)

X_train, y_train = X.iloc[:train_end], y.iloc[:train_end]
X_test, y_test = X.iloc[train_end:], y.iloc[train_end:]

# 3. Build and Train the Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=54)
clf.fit(X_train[['hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']], y_train)

# Performance
test_preds = clf.predict(X_test[['hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']])
print("Test Accuracy:", accuracy_score(y_test, test_preds))
print(classification_report(y_test, test_preds))

C:\Users\Stan\AppData\Local\Temp\ipykernel_22496\705398319.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  btc_bars['date'] = pd.to_datetime(btc_bars.index.get_level_values(1))

Test Accuracy: 0.5097142857142857
              precision    recall  f1-score   support

           0       0.52      0.44      0.47      2207
           1       0.50      0.58      0.54      2168

    accuracy                           0.51      4375
   macro avg       0.51      0.51      0.51      4375
weighted avg       0.51      0.51      0.51      4375

In [28]:
results = pd.DataFrame({'Open': X_test['open'], 'Close': X_test['close'], 'Actual': y_test, 'Predicted': test_preds})
results['Result'] = np.where(results['Actual'] == results['Predicted'], 1, 0)
results['difference'] = (results['Close'] - results['Open']) / results['Open']

results['Year'] = results.index.get_level_values(1).year
results['Month'] = results.index.get_level_values(1).month
results

                                          Open       Close  Actual  Predicted  \
symbol  timestamp
BTC/USD 2024-12-02 13:00:00+00:00   95052.1530   95714.825       1          1
        2024-11-21 11:00:00+00:00   97743.0000   97968.700       1          0
        2024-09-06 21:00:00+00:00   52817.8120   53713.366       1          1
        2025-09-16 23:00:00+00:00  116889.2000  116869.400       0          1
        2024-01-28 23:00:00+00:00   41823.9355   42050.969       1          1
...                                        ...         ...     ...        ...
        2024-11-14 18:00:00+00:00   89238.5225   89164.850       0          0
        2024-07-13 13:00:00+00:00   58764.6000   58639.801       0          1
        2024-12-08 03:00:00+00:00  100265.2585   99989.690       0          1
        2024-02-23 00:00:00+00:00   51290.1950   51432.093       1          0
        2024-02-13 00:00:00+00:00   49914.1525   50117.815       1          0

                                   Result  difference  Year  Month
symbol  timestamp
BTC/USD 2024-12-02 13:00:00+00:00       1    0.006972  2024     12
        2024-11-21 11:00:00+00:00       0    0.002309  2024     11
        2024-09-06 21:00:00+00:00       1    0.016956  2024      9
        2025-09-16 23:00:00+00:00       0   -0.000169  2025      9
        2024-01-28 23:00:00+00:00       1    0.005428  2024      1
...                                   ...         ...   ...    ...
        2024-11-14 18:00:00+00:00       1   -0.000826  2024     11
        2024-07-13 13:00:00+00:00       0   -0.002124  2024      7
        2024-12-08 03:00:00+00:00       0   -0.002748  2024     12
        2024-02-23 00:00:00+00:00       0    0.002767  2024      2
        2024-02-13 00:00:00+00:00       0    0.004080  2024      2

[4375 rows x 8 columns]

In [29]:
# Average accuracy
results['Result'].mean(), results['Actual'].mean(), results['Predicted'].mean()

(np.float64(0.5097142857142857),
 np.float64(0.4955428571428571),
 np.float64(0.5739428571428571))

In [30]:
# Calculate per year and month the number of rows and the accuracy
results.groupby('Year').agg(
    Trades=('Result', 'size'),
    Positive_trades=('Predicted', 'sum'),
    Accuracy=('Result', 'mean')
).reset_index()

   Year  Trades  Positive_trades  Accuracy
0  2024    2215             1293  0.520993
1  2025    2160             1218  0.498148

In [31]:
# Calculate the total percentage gain based on the predictions and add print it as a percentage
str(round((results[results['Predicted'] == 1].difference.sum() - results[results['Predicted'] == 0].difference.sum())*100, 1)) + '%'

'34.9%'

# Save model

In [32]:
from joblib import dump

dump(clf, "Models/RF_20260214.joblib")

['Models/RF_20260214.joblib']